//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParserCollectionTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParserCollectionTests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;success&quot;: true,
        ///	&quot;error_message&quot;: &quot;&quot;,
        ///	&quot;info&quot;: {
        ///		&quot;fields&quot;: [&quot;id&quot;, &quot;Email&quot;, &quot;Name&quot;, &quot;Surname&quot;, &quot;Phone&quot;, &quot;LastActivity&quot;],
        ///		&quot;items&quot;: [
        ///			[&quot;1&quot;, &quot;email_1@domain.com&quot;, &quot;John&quot;, &quot;Smit&quot;, &quot;+7123456789&quot;, &quot;2021-04-01 00:00:52&quot;],
        ///			[&quot;2&quot;, &quot;email_2@domain.com&quot;, &quot;Sara&quot;, &quot;Conor&quot;, &quot;+7123456711&quot;, &quot;2021-04-02 00:01:52&quot;]
        ///		]
        ///	},
        ///	&quot;error&quot;: false
        ///}.
        /// </summary>
        internal static string SeparateNameValuesExample {
            get {
                return ResourceManager.GetString("SeparateNameValuesExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;success&quot;: true,
        ///	&quot;error_message&quot;: &quot;&quot;,
        ///	&quot;info&quot;: {
        ///		&quot;fields&quot;: [&quot;id&quot;, &quot;Email&quot;, &quot;Name&quot;, &quot;Surname&quot;, &quot;Search key&quot;, &quot;Phone&quot;, &quot;LastActivity&quot;, &quot;Search key&quot;],
        ///		&quot;items&quot;: [
        ///			[&quot;1&quot;, &quot;email_1@domain.com&quot;, &quot;John&quot;, &quot;Smit&quot;, &quot;s-11&quot;, &quot;+7123456789&quot;, &quot;2021-04-01 00:00:52&quot;, &quot;s-12&quot;],
        ///			[&quot;2&quot;, &quot;email_2@domain.com&quot;, &quot;Sara&quot;, &quot;Conor&quot;, &quot;s-21&quot;, &quot;+7123456711&quot;, &quot;2021-04-02 00:01:52&quot;, &quot;s-22&quot;]
        ///		]
        ///	},
        ///	&quot;error&quot;: false
        ///}.
        /// </summary>
        internal static string SeparateNameValuesWithDoublesExample {
            get {
                return ResourceManager.GetString("SeparateNameValuesWithDoublesExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;success&quot;: true,
        ///	&quot;error_message&quot;: &quot;&quot;,
        ///	&quot;info&quot;: {
        ///		&quot;fields&quot;: [&quot;id&quot;, &quot;Email&quot;, &quot;Name&quot;, &quot;Surname&quot;, &quot;Phone&quot;, &quot;LastActivity&quot;, &quot;Tags&quot;],
        ///		&quot;items&quot;: [
        ///			[&quot;1&quot;, &quot;email_1@domain.com&quot;, &quot;John&quot;, &quot;Smit&quot;, &quot;+7123456789&quot;, &quot;2021-04-01 00:00:52&quot;, [&quot;tag_1&quot;]],
        ///			[&quot;2&quot;, &quot;email_2@domain.com&quot;, &quot;Sara&quot;, &quot;Conor&quot;, &quot;+7123456711&quot;, &quot;2021-04-02 00:01:52&quot;, [&quot;tag_1&quot;, &quot;tag_2&quot;]]
        ///		]
        ///	},
        ///	&quot;error&quot;: false
        ///}.
        /// </summary>
        internal static string SeparateNameValuesWithInnerArrays {
            get {
                return ResourceManager.GetString("SeparateNameValuesWithInnerArrays", resourceCulture);
            }
        }
    }
}
